dist: trusty
language: c
addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded=6-2017q1-1*
script:
  - make
deploy:
  skip_cleanup: true
  file_glob: true
  file: "out/debug/*.bin"
  api_key: "${GITHUB_KEY}"
  provider: releases
  overwrite: true
  on:
    tags: true
notifications:
  email: false
